version: '3.8'
services:
  onepost:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://ffsqlserver/onepostdb
    volumes:
      - ./:/app
    depends_on:
      - ffsqlserver

  ffsqlserver:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Will8.Normandy3.Forgo.A.Vehicular
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=passw0rd#
      - MYSQL_DATABASE=onepostdb
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
volumes:
  mysql_data:
  mysql_config: